import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { useState } from "react";
import { LayoutDashboard, FileText, ClipboardList, Factory, Package, Boxes, Users, Wallet, CalendarDays, Settings, Menu, X, Flame, Search, Truck } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { useAppData } from "@/lib/appStore";

const NAV=[
 ["/painel","Dashboard",LayoutDashboard],["/orcamentos","Orçamentos",FileText],["/pedidos","Pedidos",ClipboardList],["/producao","Produção",Factory],["/calendario","Calendário",CalendarDays],["/produtos","Produtos",Package],["/estoque","Estoque",Boxes],["/fornecedores","Fornecedores",Truck],["/clientes","Clientes",Users],["/financeiro","Financeiro",Wallet],["/configuracoes","Configurações",Settings]
] as const;
export function AppShell({children}:{children:React.ReactNode}){ const [open,setOpen]=useState(false); const appData=useAppData(); const [q,setQ]=useState(""); const nav=useNavigate(); const path=useRouterState({select:s=>s.location.pathname}); const menu=<nav className="flex flex-col gap-1 p-3">{NAV.map(([to,label,Icon])=><Link key={to} to={to} onClick={()=>setOpen(false)} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium",path===to||path.startsWith(to+"/")?"bg-sidebar-primary text-sidebar-primary-foreground":"text-sidebar-foreground hover:bg-sidebar-accent")}><Icon className="size-4"/>{label}</Link>)}</nav>;
 const search=(e:React.FormEvent)=>{e.preventDefault(); if(q.trim()) nav({to:"/busca",search:{q:q.trim()}});};
 return <div className="min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 hidden w-60 flex-col border-r bg-sidebar lg:flex"><div className="flex items-center gap-2.5 px-5 py-5"><div className="rounded-full bg-primary/12 p-2"><Flame className="size-5 text-primary"/></div><span className="font-display text-lg">Planejamento Lumme</span></div><div className="flex-1 overflow-y-auto">{menu}</div><div className="border-t p-3 text-xs text-muted-foreground">Dados salvos no banco do Lovable</div></aside>{open&&<div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-black/40" onClick={()=>setOpen(false)}/><aside className="absolute inset-y-0 left-0 flex w-64 flex-col bg-sidebar"><div className="flex justify-between p-4"><span className="font-display text-lg">Planejamento Lumme</span><Button variant="ghost" size="icon" onClick={()=>setOpen(false)}><X/></Button></div><div className="flex-1">{menu}</div></aside></div>}<div className="lg:pl-60"><header className="sticky top-0 z-40 flex items-center gap-3 border-b bg-background/90 px-4 py-3 backdrop-blur"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></Button><form onSubmit={search} className="relative flex-1 max-w-xl"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, pedido ou orçamento..." className="pl-9"/></form><Button variant="outline" size="sm" onClick={async()=>{await supabase.auth.signOut();nav({to:"/auth",replace:true})}}>Sair</Button></header><main className="mx-auto w-full max-w-7xl px-4 py-6 pb-16 sm:px-6">{appData.__error&&<div className="mb-4 rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">Não foi possível sincronizar com o banco de dados: {appData.__error}. Seus dados não foram descartados. Verifique o login/conexão e tente novamente.</div>}{children}</main></div></div> }
export function PageHeader({titulo,descricao,acao}:{titulo:string;descricao?:string;acao?:React.ReactNode}){return <div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-display text-2xl sm:text-3xl">{titulo}</h1>{descricao&&<p className="mt-1 text-sm text-muted-foreground">{descricao}</p>}</div>{acao}</div>}
