import {createFileRoute} from "@tanstack/react-router";
import {useMemo,useState} from "react";
import {PageHeader} from "@/components/layout/AppShell";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {getData,setData,useAppData,nextNumber,money,clienteNome,uid,type Pedido} from "@/lib/appStore";
import {toast} from "sonner";

export const Route=createFileRoute("/_authenticated/pedidos")({component:Pedidos});
const statuses=["confirmado","aguardando_producao","em_producao","pronto","aguardando_pagamento","pago","entregue","cancelado"];
const statusLabel=(s:string)=>({confirmado:"Confirmado",aguardando_producao:"Aguardando produção",em_producao:"Em produção",pronto:"Pronto",aguardando_pagamento:"Aguardando pagamento",pago:"Pago",entregue:"Entregue",cancelado:"Cancelado"}[s]??s);
const today=()=>new Date().toISOString().slice(0,10);

function Pedidos(){
 const d=useAppData();
 const [orc,setOrc]=useState(""); const [entrega,setEntrega]=useState(""); const [editId,setEditId]=useState<string|null>(null); const [expanded,setExpanded]=useState<string|null>(null); const [itemDraft,setItemDraft]=useState<Record<string,{descricao:string;quantidade:string;valor:string}>>({});
 const [search,setSearch]=useState("");
 const pedidos=useMemo(()=>d.pedidos.filter(p=>{const q=search.toLowerCase(); return !q||String(p.numero).includes(q)||clienteNome(d,p.clienteId).toLowerCase().includes(q);}),[d.pedidos,d.clientes,search]);
 function addHistory(x:any,pedidoId:string,event:string,detail:string){x.historico.push({id:uid(),pedidoId,orcamentoId:null,evento:event,detalhe:detail,criadoEm:new Date().toISOString()});}
 function converter(){const x=getData();const o=x.orcamentos.find(o=>o.id===orc);if(!o)return toast.error("Selecione um orçamento");const p:Pedido={id:uid(),numero:nextNumber(x.pedidos),clienteId:o.clienteId,data:today(),entrega:entrega||new Date(Date.now()+7*86400000).toISOString().slice(0,10),status:"confirmado",itens:o.itens,total:o.itens.reduce((s,i)=>s+i.quantidade*i.valor,0)-o.desconto,pago:0,observacao:o.observacao,checklist:[]};x.pedidos.unshift(p);o.status="convertido";addHistory(x,p.id,"Pedido criado",`Convertido do orçamento #${o.numero}`);setData(x);setOrc("");setEntrega("");toast.success(`Pedido #${p.numero} criado`)}
 function saveEdit(p:Pedido){const x=getData();const cur=x.pedidos.find(z=>z.id===p.id);if(!cur)return;const before={clienteId:cur.clienteId,entrega:cur.entrega,status:cur.status,observacao:cur.observacao,total:cur.total};cur.clienteId=p.clienteId;cur.entrega=p.entrega;cur.status=p.status;cur.observacao=p.observacao;cur.itens=p.itens;cur.total=p.itens.reduce((s,i)=>s+i.quantidade*i.valor,0);addHistory(x,p.id,"Pedido editado",`Total ${money(before.total)} → ${money(cur.total)}`);setData(x);setEditId(null);toast.success("Pedido atualizado")}
 function updateItem(p:Pedido,id:string,key:"descricao"|"quantidade"|"valor",value:string){p.itens=p.itens.map(i=>i.id===id?{...i,[key]:key==="descricao"?value:Number(value)||0}:i);setEditId(p.id)}
 function addItem(p:Pedido){p.itens=[...p.itens,{id:uid(),produtoId:"",descricao:"Novo item",quantidade:1,valor:0}];setEditId(p.id)}
 function removeItem(p:Pedido,id:string){p.itens=p.itens.filter(i=>i.id!==id);setEditId(p.id)}
 function status(id:string,status:string){const x=getData();const p=x.pedidos.find(p=>p.id===id);if(!p)return;const old=p.status;p.status=status;if(status==="entregue")p.entregueEm=new Date().toISOString();if(old!==status)addHistory(x,id,"Status alterado",`${statusLabel(old)} → ${statusLabel(status)}`);setData(x)}
 function pagar(id:string){const x=getData();const p=x.pedidos.find(p=>p.id===id);if(!p)return;const restante=Math.max(0,p.total-p.pago);if(restante<=0)return;p.pago=p.total;x.pagamentos.push({id:uid(),pedidoId:id,valor:restante,data:today(),forma:"Pix",observacao:"Pagamento registrado"});if(p.pago>=p.total)p.status="pago";addHistory(x,id,"Pagamento recebido",`Pix — ${money(restante)}`);setData(x);toast.success("Pagamento registrado")}
 function cancelar(p:Pedido){if(p.status==="cancelado")return;const x=getData();const cur=x.pedidos.find(z=>z.id===p.id);if(!cur)return;cur.status="cancelado";addHistory(x,p.id,"Pedido cancelado","O pedido permanece no histórico e não entra nos totais financeiros.");setData(x);toast.success("Pedido cancelado")}
 function excluir(p:Pedido){const x=getData();const temPag=x.pagamentos.some(pg=>pg.pedidoId===p.id);const msg=temPag?`O pedido #${p.numero} possui pagamentos registrados. Ao excluir, esses pagamentos também serão removidos.\n\nDeseja continuar?`:`Excluir definitivamente o pedido #${p.numero}?`;if(!confirm(msg))return;x.pagamentos=x.pagamentos.filter(pg=>pg.pedidoId!==p.id);x.historico=x.historico.filter(h=>h.pedidoId!==p.id);x.pedidos=x.pedidos.filter(z=>z.id!==p.id);setData(x);toast.success("Pedido excluído")}
 function duplicar(p:Pedido){const x=getData();const novo:Pedido={...structuredClone(p),id:uid(),numero:nextNumber(x.pedidos),data:today(),status:"confirmado",pago:0,checklist:[],entregueEm:undefined};novo.itens=novo.itens.map(i=>({...i,id:uid()}));x.pedidos.unshift(novo);addHistory(x,novo.id,"Pedido duplicado",`Duplicado do pedido #${p.numero}`);setData(x);toast.success(`Pedido #${novo.numero} duplicado`)}
 function imprimir(p:Pedido){const cliente=clienteNome(d,p.clienteId);const rows=p.itens.map(i=>`<tr><td>${i.descricao}</td><td>${i.quantidade}</td><td>${money(i.valor)}</td><td>${money(i.quantidade*i.valor)}</td></tr>`).join("");const w=window.open("","_blank","width=900,height=700");if(!w)return;w.document.write(`<html><head><title>Pedido #${p.numero}</title><style>body{font-family:Arial;padding:30px;color:#222}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #ddd;padding:8px;text-align:left}h1{margin-bottom:4px}.total{font-size:22px;font-weight:bold;text-align:right;margin-top:20px}</style></head><body><h1>Planejamento Lumme</h1><h2>Pedido #${p.numero}</h2><p><b>Cliente:</b> ${cliente}</p><p><b>Entrega:</b> ${p.entrega}</p><table><thead><tr><th>Item</th><th>Qtd.</th><th>Valor</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table><p class="total">Total: ${money(p.total)}</p><p>Pago: ${money(p.pago)} · Restante: ${money(Math.max(0,p.total-p.pago))}</p><p>${p.observacao||""}</p><script>window.print()</script></body></html>`);w.document.close()}
 return <><PageHeader titulo="Pedidos" descricao="Acompanhe, edite e controle cada pedido"/>
 <div className="card-artesanal p-5"><div className="grid gap-2 md:grid-cols-[1fr_180px_auto]"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={orc} onChange={e=>setOrc(e.target.value)}><option value="">Converter orçamento aprovado...</option>{d.orcamentos.filter(o=>o.status!=="convertido").map(o=><option key={o.id} value={o.id}>#{o.numero} · {clienteNome(d,o.clienteId)}</option>)}</select><Input type="date" value={entrega} onChange={e=>setEntrega(e.target.value)}/><Button onClick={converter}>Criar pedido</Button></div><div className="mt-3"><Input placeholder="Buscar por número ou cliente..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
 <div className="mt-5 grid gap-3">{pedidos.map(p=>{const editing=editId===p.id;const hist=d.historico.filter(h=>h.pedidoId===p.id);return <div className="card-artesanal p-4" key={p.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-display text-lg">Pedido #{p.numero}</h3><p className="text-sm text-muted-foreground">{clienteNome(d,p.clienteId)} · entrega {p.entrega}</p></div><b>{money(p.total)}</b></div>
 <div className="mt-3 flex flex-wrap gap-2"><select className="h-9 rounded border bg-background px-2 text-sm" value={p.status} onChange={e=>status(p.id,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select><span className="rounded bg-muted px-3 py-2 text-sm">Pago: {money(p.pago)} · Falta: {money(Math.max(0,p.total-p.pago))}</span>{p.pago<p.total&&p.status!=="cancelado"&&<Button size="sm" onClick={()=>pagar(p.id)}>Registrar restante</Button>}</div>
 <div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setEditId(editing?null:p.id)}>✏️ {editing?"Fechar edição":"Editar"}</Button><Button size="sm" variant="outline" onClick={()=>duplicar(p)}>📋 Duplicar</Button><Button size="sm" variant="outline" onClick={()=>imprimir(p)}>🖨️ Imprimir</Button>{p.status!=="cancelado"&&<Button size="sm" variant="outline" onClick={()=>cancelar(p)}>❌ Cancelar</Button>}<Button size="sm" variant="ghost" onClick={()=>excluir(p)}>🗑️ Excluir</Button><Button size="sm" variant="ghost" onClick={()=>setExpanded(expanded===p.id?null:p.id)}>📜 Histórico</Button></div>
 {editing&&<div className="mt-4 rounded-lg border bg-background p-4 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div><Label>Cliente</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={p.clienteId} onChange={e=>{p.clienteId=e.target.value;setEditId(p.id)}}>{d.clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></div><div><Label>Data de entrega</Label><Input type="date" value={p.entrega} onChange={e=>{p.entrega=e.target.value;setEditId(p.id)}}/></div></div><div><Label>Observações</Label><textarea className="min-h-20 w-full rounded-md border bg-background p-3 text-sm" value={p.observacao} onChange={e=>{p.observacao=e.target.value;setEditId(p.id)}}/></div><div className="space-y-2">{p.itens.map(i=><div key={i.id} className="grid gap-2 rounded bg-muted p-3 sm:grid-cols-[1fr_100px_120px_auto]"><Input value={i.descricao} onChange={e=>updateItem(p,i.id,"descricao",e.target.value)}/><Input type="number" min="1" step="1" value={i.quantidade} onChange={e=>updateItem(p,i.id,"quantidade",e.target.value)}/><Input type="number" min="0" step="0.01" value={i.valor} onChange={e=>updateItem(p,i.id,"valor",e.target.value)}/><Button type="button" variant="ghost" onClick={()=>removeItem(p,i.id)}>Remover</Button></div>)}</div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>addItem(p)}>+ Adicionar item</Button><Button onClick={()=>saveEdit(p)}>Salvar alterações</Button></div></div>}
 {expanded&&expanded===p.id&&<div className="mt-4 rounded-lg bg-muted p-4"><h4 className="font-semibold">Histórico do pedido</h4><div className="mt-2 space-y-2">{hist.map(h=><div key={h.id} className="text-sm"><b>{new Date(h.criadoEm).toLocaleString("pt-BR")}</b> · {h.evento}{h.detalhe&&<span className="text-muted-foreground"> — {h.detalhe}</span>}</div>)}{!hist.length&&<p className="text-sm text-muted-foreground">Nenhum evento registrado.</p>}</div></div>}
 </div>})}{!pedidos.length&&<p className="text-sm text-muted-foreground">Nenhum pedido encontrado.</p>}</div></>;
}
